
Universe       = vanilla
Notification   = Error
GetEnv         = True
Initialdir     = $ENV(PWD)
Executable     = /bin/sh
Priority       = +20
Log            = /gpfs/mnt/gpfs02/phenix/plhf/plhf1/mitran/Simul/ETA/output/LOGS/run_merge.log.$(Process)
Output         = /gpfs/mnt/gpfs02/phenix/plhf/plhf1/mitran/Simul/ETA/output/LOGS/run_merge.out.$(Process)
Error          = /gpfs/mnt/gpfs02/phenix/plhf/plhf1/mitran/Simul/ETA/output/LOGS/run_merge.err.$(Process)
Requirements   = (CPU_Speed >= 1) 
Rank		       = CPU_Speed

Arguments      = run_emc_embed.sh $(Process) 0 

Queue 200
