//
// File generated by rootcint at Mon Jan 29 20:02:19 2024

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME AnalysisDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "AnalysisDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::DstMerger DstMerger;
      #else
      class DstMerger  :  public ::SubsysReco {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~DstMerger() throw() {};
         string vtxfn; //
         ::basic_ofstream< char, ::char_traits< char >  > vtxo; //
         int runnumber; //
         int EventNumber; //
      };
      #endif

      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::SkipEvents SkipEvents;
      #else
      class SkipEvents  :  public ::SubsysReco {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~SkipEvents() throw() {};
         int Events2Skip; //
         int EventNumber; //
         float minZVertex; //
         float maxZVertex; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void DstMerger_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void DstMerger_Dictionary();
   static void *new_DstMerger(void *p = 0);
   static void *newArray_DstMerger(Long_t size, void *p);
   static void delete_DstMerger(void *p);
   static void deleteArray_DstMerger(void *p);
   static void destruct_DstMerger(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::DstMerger*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::DstMerger) == sizeof( ::ROOTShadow::Shadow::DstMerger));
      ::DstMerger *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::DstMerger),0);
      static ::ROOT::TGenericClassInfo 
         instance("DstMerger", "./DstMerger.h", 18,
                  typeid(::DstMerger), ::ROOT::DefineBehavior(ptr, ptr),
                  &DstMerger_ShowMembers, &DstMerger_Dictionary, isa_proxy, 4,
                  sizeof(::DstMerger) );
      instance.SetNew(&new_DstMerger);
      instance.SetNewArray(&newArray_DstMerger);
      instance.SetDelete(&delete_DstMerger);
      instance.SetDeleteArray(&deleteArray_DstMerger);
      instance.SetDestructor(&destruct_DstMerger);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::DstMerger*)
   {
      return GenerateInitInstanceLocal((::DstMerger*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::DstMerger*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void DstMerger_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::DstMerger*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   void SkipEvents_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void SkipEvents_Dictionary();
   static void delete_SkipEvents(void *p);
   static void deleteArray_SkipEvents(void *p);
   static void destruct_SkipEvents(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::SkipEvents*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::SkipEvents) == sizeof( ::ROOTShadow::Shadow::SkipEvents));
      ::SkipEvents *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::SkipEvents),0);
      static ::ROOT::TGenericClassInfo 
         instance("SkipEvents", "./SkipEvents.h", 8,
                  typeid(::SkipEvents), ::ROOT::DefineBehavior(ptr, ptr),
                  &SkipEvents_ShowMembers, &SkipEvents_Dictionary, isa_proxy, 4,
                  sizeof(::SkipEvents) );
      instance.SetDelete(&delete_SkipEvents);
      instance.SetDeleteArray(&deleteArray_SkipEvents);
      instance.SetDestructor(&destruct_SkipEvents);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::SkipEvents*)
   {
      return GenerateInitInstanceLocal((::SkipEvents*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SkipEvents*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void SkipEvents_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::SkipEvents*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

//______________________________________________________________________________
namespace ROOTDict {
   void DstMerger_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class DstMerger.
      typedef ::ROOTShadow::Shadow::DstMerger ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::DstMerger*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vtxfn", (void*)&sobj->vtxfn);
      R__insp.InspectMember("string", (void*)&sobj->vtxfn, "vtxfn.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vtxo", (void*)&sobj->vtxo);
      R__insp.InspectMember("ofstream", (void*)&sobj->vtxo, "vtxo.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "runnumber", &sobj->runnumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EventNumber", &sobj->EventNumber);
      R__insp.GenericShowMembers("SubsysReco", ( ::SubsysReco * )( (::DstMerger*) obj ), false);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_DstMerger(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::DstMerger : new ::DstMerger;
   }
   static void *newArray_DstMerger(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::DstMerger[nElements] : new ::DstMerger[nElements];
   }
   // Wrapper around operator delete
   static void delete_DstMerger(void *p) {
      delete ((::DstMerger*)p);
   }
   static void deleteArray_DstMerger(void *p) {
      delete [] ((::DstMerger*)p);
   }
   static void destruct_DstMerger(void *p) {
      typedef ::DstMerger current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::DstMerger

//______________________________________________________________________________
namespace ROOTDict {
   void SkipEvents_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class SkipEvents.
      typedef ::ROOTShadow::Shadow::SkipEvents ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::SkipEvents*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Events2Skip", &sobj->Events2Skip);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EventNumber", &sobj->EventNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "minZVertex", &sobj->minZVertex);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "maxZVertex", &sobj->maxZVertex);
      R__insp.GenericShowMembers("SubsysReco", ( ::SubsysReco * )( (::SkipEvents*) obj ), false);
   }

}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_SkipEvents(void *p) {
      delete ((::SkipEvents*)p);
   }
   static void deleteArray_SkipEvents(void *p) {
      delete [] ((::SkipEvents*)p);
   }
   static void destruct_SkipEvents(void *p) {
      typedef ::SkipEvents current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::SkipEvents

/********************************************************
* AnalysisDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableAnalysisDict();

extern "C" void G__set_cpp_environmentAnalysisDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("DstMerger.h");
  G__add_compiledheader("SkipEvents.h");
  G__cpp_reset_tagtableAnalysisDict();
}
#include <new>
extern "C" int G__cpp_dllrevAnalysisDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* DstMerger */
static int G__AnalysisDict_178_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DstMerger* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DstMerger[n];
     } else {
       p = new((void*) gvp) DstMerger[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DstMerger;
     } else {
       p = new((void*) gvp) DstMerger;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__AnalysisDictLN_DstMerger));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnalysisDict_178_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const DstMerger*) G__getstructoffset())->Print((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnalysisDict_178_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DstMerger*) G__getstructoffset())->setVtxAsciiFileName((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef DstMerger G__TDstMerger;
static int G__AnalysisDict_178_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (DstMerger*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((DstMerger*) (soff+(sizeof(DstMerger)*i)))->~G__TDstMerger();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (DstMerger*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((DstMerger*) (soff))->~G__TDstMerger();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* SkipEvents */
static int G__AnalysisDict_179_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SkipEvents* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new SkipEvents((int) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) SkipEvents((int) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__AnalysisDictLN_SkipEvents));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnalysisDict_179_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const SkipEvents*) G__getstructoffset())->Print((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AnalysisDict_179_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SkipEvents*) G__getstructoffset())->setZVertexRange((float) G__double(libp->para[0]), (float) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__AnalysisDict_179_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   SkipEvents* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new SkipEvents(*(SkipEvents*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__AnalysisDictLN_SkipEvents));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SkipEvents G__TSkipEvents;
static int G__AnalysisDict_179_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SkipEvents*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SkipEvents*) (soff+(sizeof(SkipEvents)*i)))->~G__TSkipEvents();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SkipEvents*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SkipEvents*) (soff))->~G__TSkipEvents();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__AnalysisDict_179_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SkipEvents* dest = (SkipEvents*) G__getstructoffset();
   *dest = *(SkipEvents*) libp->para[0].ref;
   const SkipEvents& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* DstMerger */

/* SkipEvents */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncAnalysisDict {
 public:
  G__Sizep2memfuncAnalysisDict(): p(&G__Sizep2memfuncAnalysisDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncAnalysisDict::*p)();
};

size_t G__get_sizep2memfuncAnalysisDict()
{
  G__Sizep2memfuncAnalysisDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceAnalysisDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__AnalysisDictLN_DstMerger))) {
     DstMerger *G__Lderived;
     G__Lderived=(DstMerger*)0x1000;
     {
       SubsysReco *G__Lpbase=(SubsysReco*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__AnalysisDictLN_DstMerger),G__get_linked_tagnum(&G__AnalysisDictLN_SubsysReco),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       Fun4AllBase *G__Lpbase=(Fun4AllBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__AnalysisDictLN_DstMerger),G__get_linked_tagnum(&G__AnalysisDictLN_Fun4AllBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__AnalysisDictLN_SkipEvents))) {
     SkipEvents *G__Lderived;
     G__Lderived=(SkipEvents*)0x1000;
     {
       SubsysReco *G__Lpbase=(SubsysReco*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__AnalysisDictLN_SkipEvents),G__get_linked_tagnum(&G__AnalysisDictLN_SubsysReco),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       Fun4AllBase *G__Lpbase=(Fun4AllBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__AnalysisDictLN_SkipEvents),G__get_linked_tagnum(&G__AnalysisDictLN_Fun4AllBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableAnalysisDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__AnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AnalysisDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AnalysisDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__AnalysisDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AnalysisDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnalysisDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AnalysisDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AnalysisDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* DstMerger */
static void G__setup_memvarDstMerger(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__AnalysisDictLN_DstMerger));
   { DstMerger *p; p=(DstMerger*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__AnalysisDictLN_string),-1,-1,2,"vtxfn=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__AnalysisDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR),G__defined_typename("ofstream"),-1,2,"vtxo=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"runnumber=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"EventNumber=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* SkipEvents */
static void G__setup_memvarSkipEvents(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__AnalysisDictLN_SkipEvents));
   { SkipEvents *p; p=(SkipEvents*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"Events2Skip=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"EventNumber=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,2,"minZVertex=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,2,"maxZVertex=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarAnalysisDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDstMerger(void) {
   /* DstMerger */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__AnalysisDictLN_DstMerger));
   G__memfunc_setup("DstMerger",909,G__AnalysisDict_178_0_1, 105, G__get_linked_tagnum(&G__AnalysisDictLN_DstMerger), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitRun",713,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("process_event",1408,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("End",279,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Reset",515,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ResetEvent",1029,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Print",525,G__AnalysisDict_178_0_8, 121, -1, -1, 0, 1, 1, 1, 8, "C - - 10 - what", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setVtxAsciiFileName",1912,G__AnalysisDict_178_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~DstMerger", 1035, G__AnalysisDict_178_0_10, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncSkipEvents(void) {
   /* SkipEvents */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__AnalysisDictLN_SkipEvents));
   G__memfunc_setup("SkipEvents",1036,G__AnalysisDict_179_0_1, 105, G__get_linked_tagnum(&G__AnalysisDictLN_SkipEvents), -1, 0, 1, 1, 1, 0, "i - - 0 - nevents", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitRun",713,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("process_event",1408,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("End",279,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Reset",515,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ResetEvent",1029,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Print",525,G__AnalysisDict_179_0_8, 121, -1, -1, 0, 1, 1, 1, 8, "C - - 10 - what", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setZVertexRange",1553,G__AnalysisDict_179_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"f - - 0 - a f - - 0 - b", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("SkipEvents", 1036, G__AnalysisDict_179_0_10, (int) ('i'), G__get_linked_tagnum(&G__AnalysisDictLN_SkipEvents), -1, 0, 1, 1, 1, 0, "u 'SkipEvents' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~SkipEvents", 1162, G__AnalysisDict_179_0_11, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__AnalysisDict_179_0_12, (int) ('u'), G__get_linked_tagnum(&G__AnalysisDictLN_SkipEvents), -1, 1, 1, 1, 1, 0, "u 'SkipEvents' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncAnalysisDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalAnalysisDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcAnalysisDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__AnalysisDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR = { "basic_ofstream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__AnalysisDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__AnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__AnalysisDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AnalysisDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__AnalysisDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AnalysisDictLN_Fun4AllBase = { "Fun4AllBase" , 99 , -1 };
G__linked_taginfo G__AnalysisDictLN_PHCompositeNode = { "PHCompositeNode" , 99 , -1 };
G__linked_taginfo G__AnalysisDictLN_SubsysReco = { "SubsysReco" , 99 , -1 };
G__linked_taginfo G__AnalysisDictLN_DstMerger = { "DstMerger" , 99 , -1 };
G__linked_taginfo G__AnalysisDictLN_SkipEvents = { "SkipEvents" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableAnalysisDict() {
  G__AnalysisDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__AnalysisDictLN_string.tagnum = -1 ;
  G__AnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__AnalysisDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AnalysisDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__AnalysisDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AnalysisDictLN_Fun4AllBase.tagnum = -1 ;
  G__AnalysisDictLN_PHCompositeNode.tagnum = -1 ;
  G__AnalysisDictLN_SubsysReco.tagnum = -1 ;
  G__AnalysisDictLN_DstMerger.tagnum = -1 ;
  G__AnalysisDictLN_SkipEvents.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableAnalysisDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__AnalysisDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__AnalysisDictLN_string);
   G__get_linked_tagnum_fwd(&G__AnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__AnalysisDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AnalysisDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__AnalysisDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AnalysisDictLN_Fun4AllBase);
   G__get_linked_tagnum_fwd(&G__AnalysisDictLN_PHCompositeNode);
   G__get_linked_tagnum_fwd(&G__AnalysisDictLN_SubsysReco);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__AnalysisDictLN_DstMerger),sizeof(DstMerger),-1,263424,(char*)NULL,G__setup_memvarDstMerger,G__setup_memfuncDstMerger);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__AnalysisDictLN_SkipEvents),sizeof(SkipEvents),-1,295936,(char*)NULL,G__setup_memvarSkipEvents,G__setup_memfuncSkipEvents);
}
extern "C" void G__cpp_setupAnalysisDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupAnalysisDict()");
  G__set_cpp_environmentAnalysisDict();
  G__cpp_setup_tagtableAnalysisDict();

  G__cpp_setup_inheritanceAnalysisDict();

  G__cpp_setup_typetableAnalysisDict();

  G__cpp_setup_memvarAnalysisDict();

  G__cpp_setup_memfuncAnalysisDict();
  G__cpp_setup_globalAnalysisDict();
  G__cpp_setup_funcAnalysisDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncAnalysisDict();
  return;
}
class G__cpp_setup_initAnalysisDict {
  public:
    G__cpp_setup_initAnalysisDict() { G__add_setup_func("AnalysisDict",(G__incsetup)(&G__cpp_setupAnalysisDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initAnalysisDict() { G__remove_setup_func("AnalysisDict"); }
};
G__cpp_setup_initAnalysisDict G__cpp_setup_initializerAnalysisDict;

