/********************************************************************
* AnalysisDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error AnalysisDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAnalysisDict();
extern void G__cpp_setup_inheritanceAnalysisDict();
extern void G__cpp_setup_typetableAnalysisDict();
extern void G__cpp_setup_memvarAnalysisDict();
extern void G__cpp_setup_globalAnalysisDict();
extern void G__cpp_setup_memfuncAnalysisDict();
extern void G__cpp_setup_funcAnalysisDict();
extern void G__set_cpp_environmentAnalysisDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DstMerger.h"
#include "SkipEvents.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__AnalysisDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__AnalysisDictLN_string;
extern G__linked_taginfo G__AnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__AnalysisDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnalysisDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__AnalysisDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnalysisDictLN_Fun4AllBase;
extern G__linked_taginfo G__AnalysisDictLN_PHCompositeNode;
extern G__linked_taginfo G__AnalysisDictLN_SubsysReco;
extern G__linked_taginfo G__AnalysisDictLN_DstMerger;
extern G__linked_taginfo G__AnalysisDictLN_SkipEvents;

/* STUB derived class for protected member access */
